disabled_rules:
  - colon
  - comma
  - control_statement
opt_in_rules:
  - empty_count
  - missing_docs
excluded: 
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
file_length:
  warning: 500
  error: 600
reporter: xcode